# =============================================================================
# server/audit.py -- Gemini AI audit pipeline
#
# This file is called by main.py via build_full_manifest().
# It is NOT a server itself -- it is a set of functions that main.py wraps
# in FastAPI endpoints.
#
# FUNCTIONS:
#   analyze_image(image_path)        --> dict   (battery_id object)
#   run_audit(csv_path)              --> dict   (telemetry manifest)
#   generate_openscad(battery_id)    --> str    (OpenSCAD enclosure code)
#   generate_telemetry_embedding(csv_path) --> list (float vector)
#   build_full_manifest(csv_path, image_path) --> dict (full manifest)
#
# OUTPUT SHAPE of build_full_manifest():
#   {
#     passport_id, audit_timestamp, health_grade, state_of_health_pct,
#     remaining_useful_life_years, cycle_count, peak_temp_recorded_c,
#     fast_charge_ratio_pct, thermal_stress_flag, recommended_config,
#     risk_summary, eu_compliant, status,
#     battery_id: { manufacturer, model, chemistry, rated_capacity_kwh,
#                   nominal_voltage_v, manufacture_year, serial_number },
#     openscad_code: str,       <-- 3D enclosure OpenSCAD generated by Gemini
#     telemetry_embedding: []   <-- float vector for MongoDB Atlas Vector Search
#   }
#
# ENVIRONMENT:
#   Requires GEMINI_API_KEY in server/.env
#   Loaded automatically via python-dotenv in main.py
# =============================================================================

from google import genai
from dotenv import load_dotenv
import os
import json
from pathlib import Path

load_dotenv()

client = genai.Client(api_key=os.getenv("GEMINI_API_KEY"))


def analyze_image(image_path: str) -> dict:
    """
    Reads a battery sticker image and extracts identity fields.

    Uses Gemini Vision (multimodal). The image is sent as base64-encoded
    inline data alongside a text prompt.

    Returns a dict matching the battery_id shape expected by the frontend:
      manufacturer, model, chemistry, rated_capacity_kwh,
      nominal_voltage_v, manufacture_year, serial_number

    Fields that cannot be read from the label default to:
      strings --> "unknown"
      numbers --> 0
    """
    image_bytes = Path(image_path).read_bytes()

    response = client.models.generate_content(
        model="gemini-3-flash-preview",
        contents=[
            {
                "parts": [
                    {
                        "inline_data": {
                            "mime_type": "image/jpeg",
                            "data": __import__("base64").b64encode(image_bytes).decode()
                        }
                    },
                    {
                        "text": (
                            "You are a battery identification AI for ReVolt OS.\n"
                            "Analyze this battery sticker image and return ONLY valid JSON, no explanation.\n\n"
                            "Return this exact structure:\n"
                            "{\n"
                            '  "manufacturer": "Tesla",\n'
                            '  "model": "Model 3 LR",\n'
                            '  "chemistry": "NMC",\n'
                            '  "rated_capacity_kwh": 75,\n'
                            '  "nominal_voltage_v": 350,\n'
                            '  "manufacture_year": 2020,\n'
                            '  "serial_number": "unknown"\n'
                            "}\n\n"
                            'If you cannot read a field clearly, use "unknown" for strings and 0 for numbers.'
                        )
                    }
                ]
            }
        ]
    )

    raw = response.text.strip()
    # Strip markdown code fences if Gemini wraps the output in them
    if raw.startswith("```"):
        raw = raw.split("```")[1]
        if raw.startswith("json"):
            raw = raw[4:]

    return json.loads(raw.strip())


def run_audit(csv_path: str) -> dict:
    """
    Reads a telemetry CSV and generates a health audit manifest.

    Uses Gemini text model with the full CSV content in the prompt.
    Gemini's 1M+ token context window can handle very large CSV files.

    Health grade thresholds:
      A: SOH > 90%, low thermal stress, slow charging dominant
      B: SOH 80-90%, moderate stress
      C: SOH 70-80%, high fast-charge ratio
      D/F: SOH < 70% or dangerous thermal events

    Returns a dict matching the top-level manifest shape expected by the frontend.
    Does NOT include battery_id, openscad_code, or telemetry_embedding --
    those are added by build_full_manifest().
    """
    with open(csv_path, "r") as f:
        csv_data = f.read()

    prompt = (
        "You are a battery engineering AI for ReVolt OS, a platform that certifies used EV batteries for SMEs.\n\n"
        "Analyze this battery telemetry CSV and return a JSON manifest. Return ONLY valid JSON, no explanation.\n\n"
        "CSV DATA:\n"
        + csv_data +
        "\n\nReturn this exact JSON structure:\n"
        "{\n"
        '  "passport_id": "RV-2026-001",\n'
        '  "audit_timestamp": "2026-03-21T00:00:00Z",\n'
        '  "health_grade": "B",\n'
        '  "state_of_health_pct": 82,\n'
        '  "remaining_useful_life_years": 4.2,\n'
        '  "cycle_count": 412,\n'
        '  "peak_temp_recorded_c": 54.1,\n'
        '  "fast_charge_ratio_pct": 68,\n'
        '  "thermal_stress_flag": true,\n'
        '  "recommended_config": "4S2P - bypass cell block C",\n'
        '  "risk_summary": "High fast-charge ratio detected. Thermal stress in upper cycles.",\n'
        '  "eu_compliant": true,\n'
        '  "status": "listed"\n'
        "}\n\n"
        "Base all values on the actual CSV data provided.\n"
        "Adjust health_grade (A/B/C/D/F) based on the thresholds described."
    )

    response = client.models.generate_content(
        model="gemini-3-flash-preview",
        contents=prompt
    )

    raw = response.text.strip()
    if raw.startswith("```"):
        raw = raw.split("```")[1]
        if raw.startswith("json"):
            raw = raw[4:]

    return json.loads(raw.strip())


def generate_openscad(battery_id: dict) -> str:
    """
    Generates OpenSCAD code for a 3D-printable battery enclosure.

    Called by build_full_manifest() after analyze_image() has populated
    the battery_id fields. Uses chemistry, capacity, and voltage to size
    the enclosure correctly.

    The output is stored as manifest["openscad_code"] and rendered in
    PassportCard.jsx in the "3D ENCLOSURE -- OPENSCAD" section.

    Returns a string of valid OpenSCAD code.
    If generation fails, returns an empty string (section shows pending state).
    """
    chemistry    = battery_id.get("chemistry", "unknown")
    capacity_kwh = battery_id.get("rated_capacity_kwh", 0)
    voltage_v    = battery_id.get("nominal_voltage_v", 0)

    prompt = (
        "You are a mechanical design AI for ReVolt OS.\n"
        "Generate OpenSCAD code for a 3D-printable enclosure for a battery pack with:\n"
        "  Chemistry:  " + str(chemistry) + "\n"
        "  Capacity:   " + str(capacity_kwh) + " kWh\n"
        "  Voltage:    " + str(voltage_v) + " V\n\n"
        "Requirements:\n"
        "  - Parametric design using variables at the top\n"
        "  - Wall thickness 3mm minimum\n"
        "  - Ventilation slots on top face\n"
        "  - Mounting holes on base (M4 bolts)\n"
        "  - Output ONLY valid OpenSCAD code, no explanation, no markdown fences"
    )

    try:
        response = client.models.generate_content(
            model="gemini-3-flash-preview",
            contents=prompt
        )
        code = response.text.strip()
        # Strip markdown fences if present
        if code.startswith("```"):
            code = code.split("```")[1]
            if code.startswith("openscad") or code.startswith("scad"):
                code = code.split("\n", 1)[1]
        return code.strip()
    except Exception as e:
        print(f"[WARN] OpenSCAD generation failed: {e}")
        return ""


def generate_telemetry_embedding(csv_path: str) -> list:
    """
    Generates a vector embedding of the telemetry CSV content.

    Uses the Gemini embedding model. The resulting float vector is stored
    as manifest["telemetry_embedding"] and indexed in MongoDB Atlas
    for Vector Search (semantic similarity queries across battery profiles).

    Returns a list of floats (the embedding vector).
    The vector dimension depends on the model -- gemini-embedding-001 returns 3072.
    """
    with open(csv_path, "r") as f:
        csv_data = f.read()

    response = client.models.embed_content(
        model="gemini-embedding-001",
        contents=csv_data
    )

    return response.embeddings[0].values


def build_full_manifest(csv_path: str, image_path: str) -> dict:
    """
    Orchestrates the full audit pipeline and assembles the final manifest.

    Called by main.py POST /api/audit after the uploaded files are saved
    to a temporary directory.

    Steps (in order):
      1. run_audit(csv_path)              --> telemetry manifest dict
      2. analyze_image(image_path)        --> battery_id dict
      3. generate_openscad(battery_id)    --> openscad_code string
      4. generate_telemetry_embedding()   --> float vector list

    The telemetry_embedding is intentionally excluded from the JSON file
    written to disk (manifest.json) to keep the file human-readable,
    but IS included in the dict returned to main.py / the frontend.

    Note: The embedding is large (~3072 floats). The frontend PassportCard
    does not display it -- it is stored in MongoDB for vector search only.
    """
    print("Step 1/4: Running telemetry audit...")
    telemetry = run_audit(csv_path)

    print("Step 2/4: Analyzing battery sticker...")
    battery_id = analyze_image(image_path)

    print("Step 3/4: Generating OpenSCAD enclosure...")
    openscad_code = generate_openscad(battery_id)

    print("Step 4/4: Generating telemetry embedding...")
    embedding = generate_telemetry_embedding(csv_path)

    full_manifest = {
        **telemetry,
        "battery_id":         battery_id,
        "openscad_code":      openscad_code,
        "telemetry_embedding": embedding,
    }

    # Write a human-readable version to disk (without the large embedding vector)
    readable = {k: v for k, v in full_manifest.items() if k != "telemetry_embedding"}
    with open("manifest.json", "w") as f:
        json.dump(readable, f, indent=2)

    print(f"Manifest saved to manifest.json (embedding excluded from file)")
    print(f"Embedding dimensions: {len(embedding)}")
    return full_manifest


if __name__ == "__main__":
    # Run directly for local testing:  python audit.py
    manifest = build_full_manifest("sample_telemetry.csv", "battery_sticker.jpg")
    print(json.dumps(
        {k: v for k, v in manifest.items() if k != "telemetry_embedding"},
        indent=2
    ))
